apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: llama-3-1-8b-instruct
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  resourceVersion: '1019888597'
  name: llama-3-1-8b-instruct
  namespace: ai-composer
  finalizers:
    - inferenceservice.finalizers
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--dtype=float16'
        - '--tensor-parallel-size=2'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser=llama3_json'
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '6'
          memory: 20Gi
          nvidia.com/gpu: '2'
        requests:
          cpu: '3'
          memory: 16Gi
          nvidia.com/gpu: '2'
      runtime: llama-3-1-8b-instruct
      storage:
        key: aws-connection-my-storage
        path: models/llama-3-1-8b-instruct
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
